#微服务端口号配置
server:
  port: 8081

#微服务配置文件git仓库配置
spring:
  cloud:
    config:
      discovery:
        enable: true
      server:
        encrypt:
          enabled: false
          git:
            uri: https://github.com/freeysw/conf-repo.git
            # git 配置文件根目录下目录配置
            searchPaths: zuul-service
            username: freeysw
            password: Ys19900215

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/